# Generated by Django 3.2.10 on 2022-02-10 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictSingle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('og_image', models.ImageField(upload_to='og_image')),
                ('rust_image', models.ImageField(upload_to='rust_image')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.profile')),
            ],
            options={
                'db_table': 'predict_single',
            },
        ),
        migrations.CreateModel(
            name='PredictSearches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('og_image', models.ImageField(upload_to='og_image')),
                ('rust_image', models.ImageField(upload_to='rust_image')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.profile')),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.searches')),
            ],
            options={
                'db_table': 'predict_searches',
            },
        ),
    ]
