# Generated by Django 3.2.10 on 2022-02-10 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_predictsearches_predictsingle'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictsearches',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='predictsingle',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
