# Generated by Django 3.2.10 on 2022-02-11 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20220210_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictsingle',
            name='og_image',
            field=models.ImageField(upload_to='og_image_single'),
        ),
        migrations.AlterField(
            model_name='predictsingle',
            name='rust_image',
            field=models.ImageField(upload_to='rust_image_single'),
        ),
    ]
