# Generated by Django 3.2.10 on 2022-02-11 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20220212_0213'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PredictSearches',
        ),
    ]
